const {createClient}=window.supabase;const sb=createClient(DIV_TV_CONFIG.supabaseUrl,DIV_TV_CONFIG.supabaseKey);let videos=[],series=[],current=null,user=null;
const $=s=>document.querySelector(s),toast=$('#toast');
function msg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function esc(s=''){return s.replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function card(v){const thumb=v.thumbnail_url?`<img src="${esc(v.thumbnail_url)}" alt="">`:`<div class="thumb-fallback">${esc((v.category||'DIV TV').toUpperCase())}</div>`;return `<article class="card" data-id="${v.id}"><div class="thumb">${thumb}<span>${esc(v.category||'ORIGINAL')}</span></div><h3>${esc(v.title)}</h3><p>${esc(v.series_name||v.category||'DIV TV')} · ${Number(v.views||0).toLocaleString()} views</p></article>`}
async function load(){const [{data:v,error:ve},{data:s,error:se}]=await Promise.all([sb.from('div_tv_videos').select('*,div_tv_series(title)').eq('status','published').order('published_at',{ascending:false}),sb.from('div_tv_series').select('*').order('created_at',{ascending:false})]);if(ve)console.error(ve);videos=(v||[]).map(x=>({...x,series_name:x.div_tv_series?.title||''}));series=s||[];render()}
function render(){const sorted=[...videos].sort((a,b)=>(b.views||0)-(a.views||0));$('#trendingCards').innerHTML=(sorted.length?sorted.slice(0,8):[]).map(card).join('')||'<p class="muted">No published shows yet.</p>';$('#latestCards').innerHTML=videos.slice(0,8).map(card).join('')||'<p class="muted">No published episodes yet.</p>';$('#seriesCards').innerHTML=series.map(s=>`<article class="series"><p class="eyebrow">DIV TV SERIES</p><h3>${esc(s.title)}</h3><p>${esc(s.description||'Original DIVSTUDIO stories')}</p></article>`).join('')||'<p class="muted">Series will appear here.</p>';const first=videos[0];if(first){document.querySelector('[data-watch-id]').dataset.watchId=first.id}}
function openPlayer(id){const v=videos.find(x=>x.id===id);if(!v)return;current=v;$('#playerTitle').textContent=v.title;$('#playerDescription').textContent=v.description||'';const vid=$('#videoEl');vid.src=v.video_url||'';$('#player').classList.remove('hidden');document.body.style.overflow='hidden';loadComments();sb.from('div_tv_videos').update({views:(v.views||0)+1}).eq('id',v.id).then(()=>v.views=(v.views||0)+1)}
function closePlayer(){const vid=$('#videoEl');vid.pause();vid.removeAttribute('src');vid.load();$('#player').classList.add('hidden');document.body.style.overflow=''}
async function refreshAuth(){const r=await sb.auth.getUser();user=r.data.user;$('#authBtn').textContent=user?'Account':'Sign in';$('#signOutBtn').classList.toggle('hidden',!user);$('#authSubmit').classList.toggle('hidden',!!user);$('#emailInput').classList.toggle('hidden',!!user);$('#passwordInput').classList.toggle('hidden',!!user);$('#authSwitch').classList.toggle('hidden',!!user);$('#authTitle').textContent=user?'Signed in':'Sign in'}
async function loadComments(){if(!current)return;const {data}=await sb.from('div_tv_comments').select('*').eq('video_id',current.id).eq('is_hidden',false).order('created_at',{ascending:false});$('#commentsList').innerHTML=(data||[]).map(c=>`<div class="comment"><b>${esc(c.display_name||'Viewer')}</b><p>${esc(c.body)}</p></div>`).join('')||'<p class="muted">Be the first to comment.</p>'}
async function like(){if(!user)return msg('Sign in to like videos');const {data}=await sb.from('div_tv_video_likes').select('video_id').eq('video_id',current.id).eq('user_id',user.id).maybeSingle();if(data){await sb.from('div_tv_video_likes').delete().eq('video_id',current.id).eq('user_id',user.id);$('#likeBtn').textContent='♡ Like'}else{await sb.from('div_tv_video_likes').insert({video_id:current.id,user_id:user.id});$('#likeBtn').textContent='♥ Liked'}}
async function save(){if(!user)return msg('Sign in to save videos');const {data}=await sb.from('div_tv_watch_later').select('video_id').eq('video_id',current.id).eq('user_id',user.id).maybeSingle();if(data){await sb.from('div_tv_watch_later').delete().eq('video_id',current.id).eq('user_id',user.id);$('#saveBtn').textContent='＋ Save'}else{await sb.from('div_tv_watch_later').insert({video_id:current.id,user_id:user.id});$('#saveBtn').textContent='✓ Saved'}}
$('#commentBtn').onclick=async()=>{if(!user)return msg('Sign in to comment');const body=$('#commentInput').value.trim();if(!body||!current)return;const {error}=await sb.from('div_tv_comments').insert({video_id:current.id,user_id:user.id,display_name:user.email?.split('@')[0]||'Viewer',body});if(error)msg('Could not post comment');else{$('#commentInput').value='';loadComments()}}
$('#authBtn').onclick=()=>{$('#authPanel').classList.remove('hidden');refreshAuth()};$('#closeAuth').onclick=()=>$('#authPanel').classList.add('hidden');$('#authSubmit').onclick=async()=>{const email=$('#emailInput').value.trim(),password=$('#passwordInput').value;if(!email||!password)return msg('Enter email and password');const signUp=$('#authSwitch').dataset.signup==='1';const r=signUp?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)msg(r.error.message);else{msg(signUp?'Check your email to confirm your account':'Welcome back');await refreshAuth();if(!signUp)$('#authPanel').classList.add('hidden')}};$('#authSwitch').onclick=()=>{const x=$('#authSwitch');const signup=x.dataset.signup==='1';x.dataset.signup=signup?'0':'1';$('#authTitle').textContent=signup?'Sign in':'Create account';$('#authSubmit').textContent=signup?'Sign in':'Create account'};$('#signOutBtn').onclick=async()=>{await sb.auth.signOut();await refreshAuth();msg('Signed out')};
document.addEventListener('click',e=>{const c=e.target.closest('.card');if(c)openPlayer(c.dataset.id);const w=e.target.closest('[data-watch-id]');if(w?.dataset.watchId)openPlayer(w.dataset.watchId)});$('#closePlayer').onclick=closePlayer;$('#likeBtn').onclick=like;$('#saveBtn').onclick=save;$('#shareBtn').onclick=async()=>{try{await navigator.share({title:current?.title||'DIV TV',url:location.href})}catch{await navigator.clipboard?.writeText(location.href);msg('DIV TV link copied')}};$('#subscribeBtn').onclick=async()=>{if(!user)return msg('Sign in to subscribe');const {data}=await sb.from('div_tv_subscriptions').select('user_id').eq('user_id',user.id).maybeSingle();if(data){await sb.from('div_tv_subscriptions').delete().eq('user_id',user.id);msg('Unsubscribed from DIV TV')}else{await sb.from('div_tv_subscriptions').insert({user_id:user.id});msg('Subscribed to DIV TV')}};$('#exploreBtn').onclick=()=>$('#trending').scrollIntoView();$('#libraryBtn').onclick=()=>user?msg('Your library is connected to your account'):$('#authPanel').classList.remove('hidden');
const searchPanel=$('#searchPanel'),input=$('#searchInput'),results=$('#searchResults');$('#searchBtn').onclick=()=>{searchPanel.classList.remove('hidden');input.focus()};$('#closeSearch').onclick=()=>searchPanel.classList.add('hidden');input.oninput=()=>{const q=input.value.toLowerCase().trim();const found=videos.filter(v=>(v.title+' '+v.description+' '+v.category+' '+v.tags).toLowerCase().includes(q));results.innerHTML=q?found.map(v=>`<div class="result" data-search-id="${v.id}"><b>${esc(v.title)}</b><br><span class="muted">${esc(v.category||'DIV TV')}</span></div>`).join(''):' '};results.onclick=e=>{const x=e.target.closest('[data-search-id]');if(x){searchPanel.classList.add('hidden');openPlayer(x.dataset.searchId)}};window.onkeydown=e=>{if(e.key==='Escape'){searchPanel.classList.add('hidden');closePlayer();$('#authPanel').classList.add('hidden')}};sb.auth.onAuthStateChange(()=>refreshAuth());refreshAuth();load();